### ISSUE TITLE
GPIO State Sends Down RF IO Values

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Firmware#72] opened 2017-04-11 06:23 UTC
Per the image below of the IO telemetry sent down over RF, GPIO state contains three values from RF IO.
![pasted image at 2017_04_10 10_22 pm](https://cloud.githubusercontent.com/assets/331540/24895143/b04f5858-1e43-11e7-934b-1cc09cac2145.png)

GPIO0, GPIO1, and GPIO3 are incorrectly set as P4.7, P4.6, and P4.5 respectively when compared below:
![image](https://cloud.githubusercontent.com/assets/331540/24895187/e0bf1d5c-1e43-11e7-8cf6-7a48d52c2289.png)

The correct values for the GPIO signals in question include:
![image](https://cloud.githubusercontent.com/assets/331540/24895208/0c2d4fc2-1e44-11e7-8c7b-c7ae0bf8e039.png)

This Telemetry Error was caused by [Hardware Issue #6](https://github.com/FaradayRF/FaradayRF-Hardware/issues/6)

This will affect critical applications such as the RHIT HAB which they should perform a firmware update to fix this ASAP.

The MSP430 assignment list can be found in this [Excel File](https://github.com/FaradayRF/FaradayRF-Hardware/blob/master/EngineeringDocs/ICD_REV_C.xlsx)

**Comment by kb1lqc** [comment] 2017-04-19 07:32
OK so most of this is working. It appears as though GPIO0, GPIO1, and GPIO2 are not working as expected. They are always  (1,1,0) respectively.

Per the documentation these should be the following P3.x pins. However as shown above it doesn't appear to be send down in GPIOSTATE or IOSTATE.
![image](https://cloud.githubusercontent.com/assets/331540/25168222/8aa1ae4e-2497-11e7-9374-60f39ecbce0d.png)

**Comment by kb1lqd** [comment] 2017-04-19 08:38
I forced all GPIO telemetry bits to be 0 (note that the GPIO bitshifting is NOT present in master):

![image](https://cloud.githubusercontent.com/assets/339144/25170461/73f96616-249f-11e7-83f9-f72387871d19.png)

I've confirmed the 2 stuck bits in raw unpacked telemetry:

![image](https://cloud.githubusercontent.com/assets/339144/25170357/236b7e1e-249f-11e7-934a-0ef3706fb8ca.png)

This would show up in simple UI as GPIO-6 and GPIO-7:

![image](https://cloud.githubusercontent.com/assets/339144/25170386/39e4e036-249f-11e7-9fa6-314c51c4da20.png)

I found that I can command 6 and 7 OFF:

![image](https://cloud.githubusercontent.com/assets/339144/25170981/33cb9dd2-24a1-11e7-9285-a4b837624c6c.png)

This implies the default state in ON but I do have control...

I did a soft reset using CCS and 6 and 7 returned to 1:

![image](https://cloud.githubusercontent.com/assets/339144/25171028/5b8de582-24a1-11e7-8681-31f893e99870.png)

I verified that default flash boot GPIO isn't setting these to 1's:

![image](https://cloud.githubusercontent.com/assets/339144/25171125/9bf74a5a-24a1-11e7-8a31-d8f4cae9d0be.png)

Whoops I found the gpio state further in telemetry.c that reset all by bit shifts to P4IN which is just wrong... (I commented it out for the screenshot)

![image](https://cloud.githubusercontent.com/assets/339144/25171574/2a86f4c2-24a3-11e7-94fd-ca1becc6c697.png)

@kb1lqc can you BSL this into your device: https://github.com/FaradayRF/Faraday-Firmware/blob/swissue153/Debug/Faraday_D1_Release.txt

I updated the GPIO bitmask to be manually updated correctly with both P4 and P3, I still get some odd bit flippings though now on GPIO 4 and 5. I think I need to chase down some more.

If you run telem parsing tutorial on it you should see the following test firmware version:
https://github.com/FaradayRF/Faraday-Software/tree/master/Tutorials/Python_Developer_Tutorials/foundation/Telemetry-Parsing

![image](https://cloud.githubusercontent.com/assets/339144/25173164/fcd90664-24a7-11e7-9837-4dd6b26e3d20.png)

**Comment by kb1lqd** [comment] 2017-04-19 10:10
@kb1lqc can you explain what this is doing in detail? I'm wondering if there is a parsing / shift error here.

https://github.com/kb1lqc/Faraday-Software/blob/simple_web_ui/Applications/SimpleUI/static/simpleui.js#L50

**Comment by kb1lqd** [comment] 2017-04-19 19:43
OK I found that the GPIO state was always 48 which is '0b110000' which is also HEX 0x30 or ASCII '0'

This led me to realize HDOP might have something to do with this because in the no-GPS case it is set to an array of ASCII `0`'s.

I found that AFTER I set GPIO State in telemetry framer on the MSP430 that I also copy in `telem_packet_3_struct) which holds a GPIO state... As shown below I copy IO and RF state into this struct but not GPIO state which remains ASCII '0':

![image](https://cloud.githubusercontent.com/assets/339144/25198579/db3d640a-24fc-11e7-8a4f-ba948b5712b5.png)

![image](https://cloud.githubusercontent.com/assets/339144/25198868/a84e3834-24fd-11e7-8e35-855fe091e3ef.png)

![image](https://cloud.githubusercontent.com/assets/339144/25198475/85845776-24fc-11e7-8ead-0d0c1462eabb.png)

I should even need the struct `telem` and instead directly use `telem_packet_3_struct`:

removing the unneeded `telem` variable and directly editing the telemetry frame struct:

![image](https://cloud.githubusercontent.com/assets/339144/25198868/a84e3834-24fd-11e7-8e35-855fe091e3ef.png)

I see correct GPIO output!:

![image](https://cloud.githubusercontent.com/assets/339144/25198831/8d6e6c6e-24fd-11e7-8fd2-62e688201dee.png)

**Comment by kb1lqd** [comment] 2017-04-19 20:22
@kb1lqc 

Below is the firmware that fixes:
* Updated telemetry packing function to actually pack correct GPIO State which wasn't occurring prior.

Reference: https://github.com/FaradayRF/Faraday-Firmware/tree/swissue153
Firmware File: https://github.com/FaradayRF/Faraday-Firmware/blob/swissue153/Debug/Faraday_D1_Release.txt

Please tryout out and respond.

**Comment by kb1lqd** [comment] 2017-05-07 19:18
Closing since bug was fixed in merges.

**Closed as completed by kb1lqd** 2017-05-07 19:18 UTC
Labels: bug
